spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    # SMTP 서버 호스트
    host: smtp.gmail.com
    # SMTP 서버 포트
    port: 587
    # SMTP 서버 로그인 아이디: 발신자 이메일
    username: ${MAIL_USERNAME}
    # SMTP 서버 로그인 패스워드: 앱 비밀번호
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          # SMTP 서버에 인증 필요한 경우 true로 지정한다. Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정해야 한다.
          auth: true
          # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          connectiontimeout: 5000
          # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간. 서버에서 응답이 오지 않는 경우 대기 시간을 제한하기 위해 사용된다.
          timeout: 5000
          # 클라이언트가 작업을 완료하는데 대기해야 하는 시간. 이메일을 SMTP 서버로 전송하는 데 걸리는 시간을 제한하는데 사용된다.
          writetimeout: 5000
          starttls:
            # StartTLS 활성화 여부 (기본값 : false)
            enable: true
    auth-code-expiration-millis: 3600000  # 60 * 60 * 1000 == 60분